language:
  - python
python:
  - 2.7
install:
  - pip install 'unittest2'
  - pip install "flake8${FLAKE8_VERSION}"
  - pip install 'pep8-naming'
  - pip install 'flake8-blind-except'
before_script:
  - pwd
  - ls -lah
  - pip freeze
  - flake8 --help
  - if [[ $FLAKE8_CONFIG != ".flake8" ]]; then rm .flake8; fi
  - flake8 --config $FLAKE8_CONFIG pilot.py pilot/
script:
  - unit2 -v
matrix:
  include:
  - python: 2.7
    env: FLAKE8_CONFIG=.flake8 FLAKE8_VERSION="<=3.5.0"
  exclude:
  - python: 2.7
